version: '3.7'

services:
  sample:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  mpp_backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile_backend
    # command: mvnw package && java -jar target/mpp-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
    

